/**
 * Dump SDK-generated bytes to disk for the Solidity cross-validation test.
 *
 * The Solidity test in test/integration/SdkCrossValidation.t.sol reads these
 * files via vm.readFile + vm.parseBytes and feeds them through the actual
 * ZkTlsAttestationHook. If the SDK's ABI encoding or hash formulas drift
 * from the hook's expectations, the Solidity test fails — catching any
 * cross-language regression at PR time.
 *
 * Run with:
 *   pnpm tsx scripts/dump-fixture.ts
 *
 * Files written (under <toolkit-root>/test/fixtures/):
 *   sdk-fund.hex          → ABI-encoded AttestationSpec (fund optParams)
 *   sdk-submit.hex        → ABI-encoded (Attestation[], bytes) (submit optParams)
 *   sdk-deliverable.hex   → keccak256(bytes(atts[sourceStep].data))
 *   sdk-fixture.json      → human-readable summary of what's pinned
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { runJob } from "../src/runJob.js";
import { buildSpec } from "../src/specBuilder.js";
import { encodeFundOptParams } from "../src/encoding.js";
import type { Attestation, JobBindingContext, JobDefinition } from "../src/types.js";

const PROVIDER = "0x000000000000000000000000000000000000b0b1" as const;

// The Solidity cross-validation test deploys a fresh hook with no fixed
// address, so we use a placeholder hookAddress here. The hook's
// `jobBindingFor(jobId)` view returns this same hash on chain because
// `address(this)` resolves to the test's fresh deployment address — to
// keep the fixture deterministic, the test reads the deployed address at
// runtime and pretends `CTX.hookAddress` was that same value. See the
// cross-validation test for how it threads through.
//
// In practice we just pick a stable jobId/chainId and let the Solidity
// side derive the right binding via its own `jobBindingFor`.
const CTX: JobBindingContext = {
  jobId: 1n,
  hookAddress: "0xd954517b4c4f0d3a9be69f4d4e2cbc6f30ed9d1a",
  chainId: 84532,
};

// Two-step BTC pipeline:
//   step 0: GET /coins/bitcoin       → returns {"id":"bitcoin"}
//   step 1: GET /coins/bitcoin/x     → returns {"price_usd":67234.51}
// Binding: "bitcoin" must appear in step 0.data and step 1.request.url.
const job: JobDefinition = {
  steps: [
    {
      method: "GET",
      url: "https://api.example.com/coins/bitcoin",
      responseResolves: [{ keyName: "id", parseType: "json", parsePath: "$.id" }],
      attMode: "proxytls",
    },
    {
      method: "GET",
      url: "https://api.example.com/coins/<<id>>/x",
      responseResolves: [
        { keyName: "price_usd", parseType: "json", parsePath: "$.market_data.current_price.usd" },
      ],
      attMode: "proxytls",
    },
  ],
  bindings: [
    { fromStep: 0, fromKey: "id", toStep: 1, toLocation: "url", value: "bitcoin" },
  ],
};

// Synthetic attestor: produces empty-signature attestations whose request
// shape exactly matches what the resolved spec pins. The Solidity test pairs
// this with an always-accept mock verifier; no real Primus call is made.
const dataPerStep = ['{"id":"bitcoin"}', '{"price_usd":67234.51}'];
let nextStep = 0;
const mockAttestor = async (input: {
  recipient: `0x${string}`;
  request: { url: string; method: string; header: Record<string, string>; body: string };
  responseResolves: { keyName: string; parseType: string; parsePath: string }[];
  additionParams: string;
}): Promise<Attestation> => ({
  recipient: input.recipient,
  request: {
    url: input.request.url,
    header: JSON.stringify(input.request.header),
    method: input.request.method,
    body: input.request.body,
  },
  // Mirror Primus's on-chain normalization: parseType is consumed during
  // off-chain parsing and cleared in the signed attestation.
  reponseResolve: input.responseResolves.map(r => ({ ...r, parseType: "" })),
  data: dataPerStep[nextStep++]!,
  attConditions: "",
  // Milliseconds since epoch — matches Primus's convention. Hook divides
  // by 1000 internally before comparing against block.timestamp (seconds).
  timestamp: 1700000000000n,
  additionParams: input.additionParams,
  attestors: [],
  signatures: [],
});

async function main() {
  const spec = buildSpec(job, CTX);
  const fundOptParams = encodeFundOptParams(spec);

  const { attestations, deliverable, submitOptParams } = await runJob(job, {
    ctx: CTX,
    recipient: PROVIDER,
    attestor: mockAttestor,
  });

  const fixturesDir = resolve(import.meta.dirname, "../../test/fixtures");
  mkdirSync(fixturesDir, { recursive: true });

  writeFileSync(`${fixturesDir}/sdk-fund.hex`, fundOptParams);
  writeFileSync(`${fixturesDir}/sdk-submit.hex`, submitOptParams);
  writeFileSync(`${fixturesDir}/sdk-deliverable.hex`, deliverable);
  writeFileSync(
    `${fixturesDir}/sdk-fixture.json`,
    JSON.stringify(
      {
        provider: PROVIDER,
        job,
        spec: {
          stepCount: spec.steps.length,
          bindingCount: spec.bindings.length,
          deliverableSourceStep: spec.deliverableSourceStep,
        },
        attestationCount: attestations.length,
        deliverable,
      },
      (_k, v) => (typeof v === "bigint" ? v.toString() : v),
      2,
    ),
  );

  console.log("wrote fixtures to", fixturesDir);
  console.log("  sdk-fund.hex        :", fundOptParams.slice(0, 18), "...");
  console.log("  sdk-submit.hex      :", submitOptParams.slice(0, 18), "...");
  console.log("  sdk-deliverable.hex :", deliverable);
}

void (dirname(import.meta.dirname), main());
