// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {
    ZkTlsAttestationHook,
    Attestation
} from "@erc8183-hooks/hooks/ZkTlsAttestationHook.sol";
import {IERC8183Hook} from "@erc8183/IERC8183Hook.sol";

contract MockCore {
    struct JobView {
        address client; uint8 status; address provider; uint48 expiredAt;
        address evaluator; uint48 submittedAt; uint256 budget; address hook;
        address paymentToken; uint256 providerAgentId; string description;
    }
    mapping(uint256 => JobView) public jobs;
    function setJob(uint256 jobId, address hookAddr) external {
        jobs[jobId] = JobView({
            client: address(0xc1), status: 0, provider: address(0xb0b1),
            expiredAt: uint48(block.timestamp + 1 days), evaluator: address(0xe0e),
            submittedAt: 0, budget: 0, hook: hookAddr,
            paymentToken: address(0), providerAgentId: 0, description: ""
        });
    }
    function getJob(uint256 jobId) external view returns (JobView memory) { return jobs[jobId]; }
    function callBefore(IERC8183Hook hook, uint256 jobId, bytes4 sel, bytes calldata d) external {
        hook.beforeAction(jobId, sel, d);
    }
    function callAfter(IERC8183Hook hook, uint256 jobId, bytes4 sel, bytes calldata d) external {
        hook.afterAction(jobId, sel, d);
    }
}

contract AcceptingVerifier {
    function verifyAttestation(Attestation calldata) external pure {}
}

/// @notice Closes the loop between the TypeScript SDK and the Solidity hook:
///
///         The SDK script `sdk/scripts/dump-fixture.ts` produces the
///         fund optParams, submit optParams, and deliverable for a 2-step
///         BTC-pipeline job. This test feeds those EXACT bytes — generated
///         off-chain by the SDK — into the actually-deployed hook and
///         asserts the on-chain validation accepts them.
///
///         Any drift between the SDK's ABI encoding / hash formulas and the
///         hook's expectations surfaces as a hard test failure here, not as
///         a silent failure on testnet.
///
///         Regenerate the fixtures whenever the SDK or hook changes:
///             cd sdk && pnpm tsx scripts/dump-fixture.ts
contract SdkCrossValidationTest is Test {
    bytes4 internal constant SEL_FUND = bytes4(keccak256("fund(uint256,uint256,bytes)"));
    bytes4 internal constant SEL_SUBMIT = bytes4(keccak256("submit(uint256,bytes32,bytes)"));

    address internal constant PROVIDER = 0x000000000000000000000000000000000000b0b1;
    address internal constant CLIENT   = address(0xc1);
    uint256 internal constant JOB_ID   = 1;

    MockCore internal core;
    AcceptingVerifier internal zkVerifier;
    ZkTlsAttestationHook internal hook;

    function setUp() public {
        core = new MockCore();
        zkVerifier = new AcceptingVerifier();
        hook = new ZkTlsAttestationHook(address(core), address(zkVerifier));
        core.setJob(JOB_ID, address(hook));
        // The fixture stamps att.timestamp = 1700000000000 ms; the hook
        // divides by 1000 and then enforces maxAge=300 s, so we warp
        // close to 1700000000 s = 60 s after the attestation moment.
        vm.warp(1700000000 + 60);
    }

    function test_SdkFixture_FlowsThroughHook() public {
        bytes memory fundOptParams = vm.parseBytes(vm.readFile("test/fixtures/sdk-fund.hex"));
        bytes memory submitOptParams = vm.parseBytes(vm.readFile("test/fixtures/sdk-submit.hex"));
        bytes32 deliverable = vm.parseBytes32(vm.readFile("test/fixtures/sdk-deliverable.hex"));

        // 1) Drive the configuration path: SDK's fund optParams ABI-decoded
        //    by the hook's `_postFund`. If the spec encoding diverged from
        //    what the hook expects, this would revert during abi.decode.
        bytes memory fundData = abi.encode(CLIENT, fundOptParams);
        core.callAfter(IERC8183Hook(address(hook)), JOB_ID, SEL_FUND, fundData);

        // 2) Drive the validation path: SDK's submit optParams + deliverable
        //    consumed by the hook's `_preSubmit`. Every hash check inside
        //    `_verifyOneStep` and every binding substring check must succeed
        //    for this call not to revert — that is the cross-language
        //    contract we're enforcing.
        bytes memory submitData = abi.encode(PROVIDER, deliverable, submitOptParams);
        core.callBefore(IERC8183Hook(address(hook)), JOB_ID, SEL_SUBMIT, submitData);

        assertTrue(hook.isValidated(JOB_ID), "hook accepted SDK-generated bytes");
    }
}
